"""Plan generator — produces Markdown refactoring plans from debt instances.

Given a list of ``DebtInstance`` objects (from ``DebtDetector.detect()`` or
a ``DebtRegistry`` snapshot), produces a prioritised Markdown plan document
suitable for PR descriptions, team reviews, or sprint planning.

Priority ordering:

1. **God Functions** — highest risk, block testability.
2. **God Classes** — high coupling, hard to maintain.
3. **Deep Nesting** — readability risk, medium effort.
4. **Long Parameter Lists** — design smell, low effort fix.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from typing import Any

from code_audit.model.debt_instance import DebtInstance, DebtType

# Priority ordering (lower = more urgent)
_PRIORITY: dict[DebtType, int] = {
    DebtType.GOD_FUNCTION: 1,
    DebtType.GOD_CLASS: 2,
    DebtType.DEEP_NESTING: 3,
    DebtType.FEATURE_ENVY: 4,
    DebtType.LONG_PARAMETER_LIST: 5,
    DebtType.DATA_CLUMP: 6,
}

_EFFORT: dict[DebtType, str] = {
    DebtType.GOD_FUNCTION: "Medium (1–3 hours)",
    DebtType.GOD_CLASS: "High (3–8 hours)",
    DebtType.DEEP_NESTING: "Low (30–60 min)",
    DebtType.FEATURE_ENVY: "Medium (1–2 hours)",
    DebtType.LONG_PARAMETER_LIST: "Low (15–30 min)",
    DebtType.DATA_CLUMP: "Low (30–60 min)",
}


def generate_plan(
    debt_items: list[DebtInstance],
    *,
    project_id: str = "",
) -> str:
    """Render a Markdown refactoring plan from debt instances.

    Parameters
    ----------
    debt_items:
        Detected debt instances (from ``DebtDetector.detect()``).
    project_id:
        Optional project identifier for the header.

    Returns
    -------
    str
        Complete Markdown document.
    """
    if not debt_items:
        return _empty_plan(project_id)

    lines: list[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ── header ──────────────────────────────────────────────────────
    lines.append("# Strangler Fig — Refactoring Plan")
    lines.append("")
    lines.append(f"**Generated:** {now}  ")
    if project_id:
        lines.append(f"**Project:** {project_id}  ")
    lines.append(f"**Debt items:** {len(debt_items)}  ")
    lines.append("")

    # ── summary table ───────────────────────────────────────────────
    type_counts = Counter(d.debt_type for d in debt_items)
    lines.append("## Summary")
    lines.append("")
    lines.append("| Debt Type | Count | Priority | Effort |")
    lines.append("|-----------|------:|----------|--------|")
    for dtype in sorted(type_counts, key=lambda d: _PRIORITY.get(d, 99)):
        count = type_counts[dtype]
        pri = _PRIORITY.get(dtype, 99)
        effort = _EFFORT.get(dtype, "Unknown")
        lines.append(f"| {dtype.value} | {count} | P{pri} | {effort} |")
    lines.append("")

    # ── prioritised work items ──────────────────────────────────────
    sorted_items = sorted(
        debt_items,
        key=lambda d: (_PRIORITY.get(d.debt_type, 99), d.path, d.line_start),
    )

    lines.append("## Work Items")
    lines.append("")

    current_type: DebtType | None = None
    item_num = 0
    for item in sorted_items:
        if item.debt_type != current_type:
            current_type = item.debt_type
            pri = _PRIORITY.get(current_type, 99)
            lines.append(f"### P{pri} — {current_type.value}")
            lines.append("")

        item_num += 1
        loc = f"`{item.path}:{item.line_start}`"
        lines.append(f"**{item_num}. {item.symbol}** ({loc})")
        lines.append("")

        # Metrics
        if item.metrics:
            metric_parts = [f"{k}={v}" for k, v in item.metrics.items()]
            lines.append(f"- **Metrics:** {', '.join(metric_parts)}")

        # Strategy
        if item.strategy:
            lines.append(f"- **Strategy:** {item.strategy}")

        # Effort
        effort = _EFFORT.get(item.debt_type, "Unknown")
        lines.append(f"- **Estimated effort:** {effort}")
        lines.append("")

    # ── footer ──────────────────────────────────────────────────────
    lines.append("---")
    lines.append(
        "*Plan generated by code-audit strangler module. "
        "Tackle items top-down for maximum impact.*"
    )
    lines.append("")

    return "\n".join(lines)


def _empty_plan(project_id: str) -> str:
    """Return a short plan when no debt is detected."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = f"# Strangler Fig — Refactoring Plan\n\n**Generated:** {now}  \n"
    if project_id:
        header += f"**Project:** {project_id}  \n"
    header += "\n**No structural debt detected.** The codebase is clean.\n"
    return header
